### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by mushroomeo** [UPBGE/upbge#1159]
now since 1 week latest UPBGE eevee keeps crashing if i open it and first click somewhere in 3D viewport or crashed if i run BGE and then esc

latest blender 2.83 alpha doesnt crash

**Comment by youle31** [comment]
I can't reproduce this crash.

Without more informations, we can do nothing.

What you can do on your side is to download all old builds (from ~1 week ago) of lordloki here: https://mega.nz/#F!k9MW1KiZ!UOKzjh3IQ0GEgjQ6GUc7ug!YsshHCha

and tell us exactly since what build you have a crash (we could have a look at if we see a merge mistake or something in the commit log).

You can also try to clean your environment (remove all what is in C:\Users\yourName\AppData\Roaming\upbge (it will remove all your preferences/addons)) and retry to load upbge.

**Comment by BluePrintRandom** [comment]
I get the same crash,

I play / stop, play / stop, click the viewport and I get a crash

**Comment by youle31** [comment]
I manage to reproduce the crash clicking everywhere and pressing P then escape very fast..., i'm downloading lordloki builds from 10 days ago...

**Comment by youle31** [comment]
I think this happens between 13 and 17 march. I'll take a look at commit log.
Maybe something related to interface? I remember some conflicts in interface_handlers.c... we'll see

**Comment by youle31** [comment]
Fixed here: https://github.com/UPBGE/upbge/commit/02e1a04042cfbebb93e93ef9c4b7c63498ae5c8a

**Comment by BluePrintRandom** [comment]
thank you youle!

**Comment by mushroomeo** [comment]
thanks much it fixed but not fully. if i open UPBGE and click on viewport it still crashes but only sometimes now. figured out that the faster after blender loads i click the more chance is to crash.
if i load file and immediatly click somewhere in viewport then it crashes almost everytime

also i see if i run BGE the objects in outliner flicker like it would repeatedly reselecting all the time. but sometimes too only

**Comment by youle31** [comment]
I can't reproduce this (the crash)... Are you sure this doesn't happen in last 2.83 alpha too?

About flickering, yes, this is known and i didn't find a proper fix for that but i added a button in render tab named "UI anti flicker" to avoid the scissor test which generates the bug.

**Comment by mushroomeo** [comment]
well just tryed latest 2.83 and i cant get this crash. but maybe its not so bad since it happens very rare now so i can live with that. and i cant reproduce it always dont know why
