### ISSUE TITLE
Depth Transparency: EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by UnidayStudio** [UPBGE/upbge#657]
My friend is having a problem since the UPBGE 0.1.7: 
Everytime that my friend clicks on the Depth Transparency checkbox, the blender closes and printed the error: EXCEPTION_ACCESS_VIOLATION. (Probabily some memory leak). 
When my friend tries to activate this on the 0.1.6, save and open the .blend on 0.1.7+, the blender crashes instantly, with the same error.
Running on Windows 7 Ultimate 64 bits.

**Comment by panzergame** [comment]
Hello, could you provide a simple blend test file (I have no issue here) ? Also the bug is happening always or after some runs ?

**Comment by joelgomes1994** [comment]
Running on Windows 7 Ultimate too, but can't reproduce the bug, maybe has been fixed along with the #661

**Comment by panzergame** [comment]
@UnidayStudio : Is the issue still actual with recent versions ?

**Comment by UnidayStudio** [comment]
@panzergame Yes. Tested on 0.2.3 today and the issue still actual. But I coudn't find out a way to reproduce the bug yet (it happens on my friend's computer). It seems to be ok on UPBGE 0.1.6 and crashing on 0.1.7 or superior.

By simple opening blender and activating the Depth Transparency in any material, blender closes.

**Comment by panzergame** [comment]
What OpenGL version and extensions are used ?

**Comment by UnidayStudio** [comment]
Here is the PC specs:
-CPU: Core 2 quad q6600
-RAM: 4gb ram
-GPU: Hd 4670
-OS: windows 7 ultimate 64 bits

Aparently, this GPU only supports OpenGL 2.0, DirectX 10.1

**Comment by panzergame** [comment]
Do you have messages in console ?

**Comment by lordloki** [comment]
It works in 0.2.5. Checked in 3 computers.
Closing. Thanks for reporting.
